//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab01
{


    public partial class DangKyThanhVien
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtTendn;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTendn;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revTendn;

        protected global::System.Web.UI.WebControls.TextBox txtMatkhau;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMatkhau;

        protected global::System.Web.UI.WebControls.TextBox txtNhaplai;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNhaplai;
        protected global::System.Web.UI.WebControls.CompareValidator cvNhaplai;

        protected global::System.Web.UI.WebControls.TextBox txtHoten;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvHoten;

        protected global::System.Web.UI.WebControls.DropDownList ddlNgay;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNgay;

        protected global::System.Web.UI.WebControls.DropDownList ddlThang;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvThang;

        protected global::System.Web.UI.WebControls.DropDownList ddlNam;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNam;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        protected global::System.Web.UI.WebControls.TextBox txtThunhap;
        protected global::System.Web.UI.WebControls.RangeValidator rvThunhap;

        protected global::System.Web.UI.WebControls.CheckBox chkNam;

        protected global::System.Web.UI.WebControls.TextBox txtDiachi;

        protected global::System.Web.UI.WebControls.TextBox txtDienthoai;

        protected global::System.Web.UI.WebControls.Button butDangky;

        protected global::System.Web.UI.WebControls.ValidationSummary vsBangloi;
        protected global::System.Web.UI.WebControls.Label lblHoso;
    }
}
